import Header from "@/components/header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen min-w-dvw")}>
        <Header className="hidden " />
        {children}
        <footer>
          <div className="container sticky bottom-0 h-16">
            <p>
              &copy; 2024 Created by{" "}
              <span className="font-bold underline underline-offset-2">
                darmaT0o0
              </span>{" "}
              Hosting by Vercel
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
